# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - SmartShopper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://xmycontainerregistryx.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b4fc3821c2754485a474ea06d5ec1c73 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_29404a3a19934c5fa4b1f6ab7a0441d1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: xmycontainerregistryx.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b4fc3821c2754485a474ea06d5ec1c73 }}/ecommercesmartshopper:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SmartShopper'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_02d1061a9a674d19a67fa0941cca8232 }}
        images: 'xmycontainerregistryx.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b4fc3821c2754485a474ea06d5ec1c73 }}/ecommercesmartshopper:${{ github.sha }}'